version: '3'
services:
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgrest:postgrest@db:5432/postgrest
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_JWT_SECRET: "@/keys.json"
      PGRST_JWT_SECRET_IS_BASE64: false
      PGRST_ROLE_CLAIM_KEY: ".roles[0]"
      PGRST_LOG_LEVEL: info
      PGRST_OPENAPI_SECURITY_ACTIVE: true
    volumes:
      - ${PWD}/keys.json:/keys.json
    depends_on:
      - db
      
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgrest
      POSTGRES_USER: postgrest
      POSTGRES_PASSWORD: postgrest
    volumes:
      - ${PWD}/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/